version: '3'

services:
  py-apiens-postgres-test:
    image: postgres:latest
    restart: always
    ports:
      - '127.0.0.1:54321:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_apiens
      