version: '3'

services:
  py-myproject-postgres-test:
    image: postgres:latest
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_myproject
