[tool.poetry]
name = "apiens"
version = "0.0.0"
description = ""
authors = ["Mark Vartanyan <kolypto@gmail.com>"]
repository = 'https://github.com/kolypto/py-apiens'

[tool.poetry.dependencies]
python = "^3.8"
pydantic = {version = "^1.6.1", optional = true}
fastapi = {version = "^0.61.1", optional = true}

[tool.poetry.dev-dependencies]
nox = "^2020.8.22"
pytest = "^6.0.1"
pytest-cov = "^2.10.1"
pydantic = "^1.6.1"
fastapi = "^0.61.1"

[tool.pytest.ini_options]
testpaths = [
    "tests/",
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
